### ISSUE TITLE
"What's New" formatting wrong/missing

### ISSUE THREAD

**Issue by runofthemill** [alefragnani/vscode-whats-new#5]
Hi there! 

I just installed the extension, and not sure if this is related to #3 but formatting seems to be wrong/missing (including broken header image) in my VS Code:

![Screen Shot 2020-06-01 at 9 21 12 AM](https://user-images.githubusercontent.com/8418440/83429820-83132980-a3e9-11ea-9071-7420799ca964.png)

Output from VS Code -> About Visual Studio Code -> Copy:

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

Let me know if there's anything else helpful I can provide!

Cheers

**Comment by alefragnani** [comment]
Hi @runofthemill ,

Yes, exactly. But in fact, it’s an error _caused by_ VS Code. The error started to happen with the latest VS Code release, with a lot of other extensions too.

It appears something has changed in VS Code internals (probably because the recent changes for remote development), creating breaking changes for extension developers. Then, they updated the API and extensions need to update as well. You can find more details on issues like this (https://github.com/microsoft/vscode/issues/89038) and related issues.

The VS Code team created another issue to track extensions that have adopted the new API (https://github.com/microsoft/vscode/issues/97962), and I asked if they will release the new API as _stable_ in the next monthly release, but I didn’t have an answer yet :sad:.

Thanks for reporting.
